# Generated by Django 5.2.3 on 2025-06-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
