# Generated by Django 5.2.3 on 2025-06-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_delete_student_delete_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, help_text='Assigned area for teachers', max_length=100, null=True),
        ),
    ]
