# Generated by Django 5.2.3 on 2025-06-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_students',
            field=models.BooleanField(default=True, help_text='Whether teacher can add new students'),
        ),
    ]
